import axios from "axios"

export const CREATE_USER_START = "CREATE_USER_START"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"

export const POST_PLANT_START = "POST_PLANT_START"
export const POST_PLANT_SUCCESS = "POST_PLANT_SUCCESS"
export const POST_PLANT_FAIL = "POST_PLANT_FAIL"

export const UPDATE_PLANT_START = "UPDATE_PLANT_START"
export const UPDATE_PLANT_SUCCESS = "UPDATE_PLANT_SUCCESS"
export const UPDATE_PLANT_FAIL = "UPDATE_PLANT_FAIL"

